### ISSUE TITLE
Add multi-Radarr sync support

### ISSUE THREAD

**Issue by keldian** [santiagosayshey/Profilarr#1]
Hello and thanks for maintaining this.

Currently the script processes a single Radarr instance, but I'm using it to sync other Radarr instances CF's with the main one's, by changing the URL/API key on every run.

I'd like to suggest being able to define multiple URL/API key blocks (in a dedicated config file), one being set as "master", such that the script will export CFs and profiles from it and import them into the other defined instances in a single run.

**Comment by santiagosayshey** [comment]
Hi, sorry its taken so long (uni, motivation, etc). I've implemented radarr / sonarr syncing with this PR. Let me know what you think / if anything needs to be changed / added! @keldian

**Comment by keldian** [comment]
Cheers, I'll give it a spin soon.
