### ISSUE TITLE
Quality Profiles can be imported before custom formats are imported

### ISSUE THREAD

**Issue by santiagosayshey** [santiagosayshey/Profilarr#11]
**Description:**
Quality Profiles can be imported before the proper custom formats, leading to an empty quality profile.

**Steps to Reproduce:**
1. Don't import custom formats
2. Import a quality profile

**Expected Behavior:**
The custom formats are automatically imported before the quality profiles are imported.

**Actual Behavior:**
Custom formats need to be manually imported.

**Comment by marshes** [comment]
I spun an LXC up yesterday to be able to run profilarr and try the project out. It seems really promising and can’t wait for more profiles to be built out.

I might suggest making an additional sync choice that would do both actions in one command: sync formats then profiles all in one go?

**Comment by santiagosayshey** [comment]
> I spun an LXC up yesterday to be able to run profilarr and try the project out. It seems really promising and can’t wait for more profiles to be built out.
> 
> I might suggest making an additional sync choice that would do both actions in one command: sync formats then profiles all in one go?

Hi, thanks for the feedback!

Do you mean the actual sync tool i.e. Syncing a master instance to extra instances? If so, that's already implemented :)

If you meant importing to a single instance in a single command, then yep I will absolutely be implementing this soon!

**Comment by marshes** [comment]
Yup, sync wasn't the best word choice, import is what I meant. I only have one instance of each app currently, and thought it would be nice if the script took care of everything I wanted in one step. Along those lines, any configured service (of either type) could also be updated in 1 step. Could see that being useful for when new or updates to profiles come out, it could be a single step to update both actions on all services -and even wiping all older profiles as suggested in a different discussion.

Regardless, cool to hear you're working on usability improvements in addition to building out scope!

**Comment by santiagosayshey** [comment]
> long those lines, any configured service (of either type) could also be updated in 1 step

Great idea! Added to the to do list. 

Cheers :)

**Comment by santiagosayshey** [comment]
I've implemented this in the latest develop build!

Should be out in a release later this week :)

**Comment by santiagosayshey** [comment]
Put out 0.3 a bit earlier because of a bug I found!
