### ISSUE TITLE
Feature Request: Option to delete *all* existing Custom Formats

### ISSUE THREAD

**Issue by markhaines** [santiagosayshey/Profilarr#12]
I'm moving from Trash Guides across to this and it would be nice to have the option configurable to 'clean the deck' of Sonarr and Radarr first before importing the new Custom Formats to have the script bullk delete all the existing Custom Formats - it seems really laborious to click in and delete them all manually.

**Comment by santiagosayshey** [comment]
Hi, thanks for the feedback :)

I'll have to make sure this is possible to implement before confirming, but this is something that I would like to add. If it is possible, it will most likely be implemented as extra functionality in the form of a new command - _deletarr_. 

In the meantime, you should be able to import the new custom formats, it will just overwrite your old ones. 

Furthermore, I'm working on issue #10 currently, which will allow you to import all the Dictionarry custom formats with unique names which will also (hopefully) fix your issue.

**Comment by santiagosayshey** [comment]
Feature implemented in PR #20 !

**Comment by markhaines** [comment]
Working perfectly - thanks!
