### ISSUE TITLE
Cannot import profiles 

### ISSUE THREAD

**Issue by EliasGagnef** [santiagosayshey/Profilarr#3]
Tried both the Windows Store and website Python versions in Windows 11, both do in this:

```
PS W:\stuff\Profilarr\Profilarr-0.2.1> py importarr.py
Enter the app you want to import to (radarr/sonarr): radarr

Choose what to import:
1. Custom Formats
2. Quality Profiles
Enter your choice (1/2): 2
Traceback (most recent call last):
  File "C:\Users\Aylesburys\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aylesburys\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aylesburys\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aylesburys\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\stuff\Profilarr\Profilarr-0.2.1\importarr.py", line 219, in <module>
    import_quality_profiles(source_config)
  File "W:\stuff\Profilarr\Profilarr-0.2.1\importarr.py", line 119, in import_quality_profiles
    cf_import_sync(source_config)
  File "W:\stuff\Profilarr\Profilarr-0.2.1\importarr.py", line 196, in cf_import_sync
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Aylesburys\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
PS W:\stuff\Profilarr\Profilarr-0.2.1>
```

I'm probably doing something wrong :p, sorry if that is the case I have no idea what I'm doing, still thank you so much for this project it's super awesome :) Really excited to get it working with my Sonarr and Radarr

**Comment by santiagosayshey** [comment]
Hi, are you on the latest stable versions of radarr / sonarr? @EliasGagnef 

I've tried recreating this on my local machine without any luck so I'm a bit stumped here :/

But we'll figure this out!

**Comment by EliasGagnef** [comment]
> Hi, are you on the latest stable versions of radarr / sonarr? Were you able to import the custom formats successfully?
> 
> I've tried recreating this on my local machine without any luck so I'm a bit stumped here :/
> 
> But we'll figure this out! @EliasGagnef

Thank you so much :) I am using the Docker Preview versions I think, do you need to import the custom formats somehow  before running py importarr.py? The first command I ran was the importarr.py

**Comment by santiagosayshey** [comment]
^ ignore that. Referenced the wrong issue.

> Thank you so much :) I am using the Docker Preview versions I think, do you need to import the custom formats somehow before running py importarr.py? The first command I ran was the importarr.py

Yes, you'll need to run `py importarr.py` first, then choose your preferred app, then select `1. Custom Formats`.

If that doesn't work, would you mind sharing the exact versions of Radarr / Sonarr you're using? If you're using a docker compose file it would say something like: `image: linuxserver/radarr:latest`

I just wondering if you also had the same issue in both apps? Or is it just one of them?

We'll get to the bottom of this! Cheers

**Comment by EliasGagnef** [comment]
> > Thank you so much :) I am using the Docker Preview versions I think, do you need to import the custom formats somehow before running py importarr.py? The first command I ran was the importarr.py
> 
> Yes, you'll need to run `py importarr.py` first, then choose your preferred app, then select `1. Custom Formats`.
> 
> If that doesn't work, would you mind sharing the exact versions of Radarr / Sonarr you're using? If you're using a docker compose file it would say something like: `image: linuxserver/radarr:latest`
> 
> I was also wondering if you also had the same issue in both apps? Or is it just one of them?
> 
> Have you installed the requirements?
> 
> We'll get to the bottom of this! Cheers

Thank you so much for the help :) I am now getting this error:
```
PS W:\stuff\Profilarr\Profilarr-0.2.3> py importarr.py
Traceback (most recent call last):
  File "W:\stuff\Profilarr\Profilarr-0.2.3\importarr.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
But I fixed this by running `pip install pyyaml` :)

I didn't know that I had to run the `1. Custom Formats` before the second option, thank you so much it works now :D Maybe it would be a good idea to add that the script will crash if you run the 2nd command without ever running the first one? Or maybe not since I'm probably the only one who misunderstood :p

**Comment by EliasGagnef** [comment]
I am now having this issue as well, for anything that isn't 4k (and on worse quality 4k releases), the score is minus a lot lol, did I do something wrong? I chose 2160p optimal and this happens on both Radarr and Sonarr
![bild](https://github.com/santiagosayshey/Profilarr/assets/46574798/ae214868-4cea-4de8-89aa-9255732c7a8d)

**Comment by santiagosayshey** [comment]
> I didn't know that I had to run the 1. Custom Formats before the second option, thank you so much it works now :D Maybe it would be a good idea to add that the script will crash if you run the 2nd command without ever running the first one? Or maybe not since I'm probably the only one who misunderstood :p

Haha no worries. This is something I'm planning on implementing in the next update! 

> I am now having this issue as well, for anything that isn't 4k (and with worse quality 4k releases), the score is minus a lot lol, did I do something wrong? I chose 2160p optimal and this happens on both Radarr and Sonarr ![bild](https://private-user-images.githubusercontent.com/46574798/300229654-ae214868-4cea-4de8-89aa-9255732c7a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTk5NTgsIm5iZiI6MTcwNjQxOTY1OCwicGF0aCI6Ii80NjU3NDc5OC8zMDAyMjk2NTQtYWUyMTQ4NjgtNGNlYS00ZGU4LTg5YWEtOTI1NTczMmM3YThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA1MjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTUwNzNmOTkyZjcyYTc5Nzc1OTQ5Njk3M2ZlMDMxYWQ0OGUwODQ3NmFhNjg1YjcyODA3ZWJiNmQ5YjNiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d_HL8AaP6MDXObpLyjdlVTMkBLc0ICaiITfAEwRlEnw)

Yes that's intended. 4k Optimal allows only remuxes and web-dls.

**Comment by EliasGagnef** [comment]
> > I didn't know that I had to run the 1. Custom Formats before the second option, thank you so much it works now :D Maybe it would be a good idea to add that the script will crash if you run the 2nd command without ever running the first one? Or maybe not since I'm probably the only one who misunderstood :p
> 
> Haha no worries. This is something I'm planning on implementing in the next update! And just for future reference, the README will have the requried information on setting everything up!
> 
> `run pip install -r requirements.txt to install dependencies` this line would have installed all the libraries you needed to run it.
> 
> > I am now having this issue as well, for anything that isn't 4k (and with worse quality 4k releases), the score is minus a lot lol, did I do something wrong? I chose 2160p optimal and this happens on both Radarr and Sonarr ![bild](https://private-user-images.githubusercontent.com/46574798/300229654-ae214868-4cea-4de8-89aa-9255732c7a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTk5NTgsIm5iZiI6MTcwNjQxOTY1OCwicGF0aCI6Ii80NjU3NDc5OC8zMDAyMjk2NTQtYWUyMTQ4NjgtNGNlYS00ZGU4LTg5YWEtOTI1NTczMmM3YThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA1MjczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTUwNzNmOTkyZjcyYTc5Nzc1OTQ5Njk3M2ZlMDMxYWQ0OGUwODQ3NmFhNjg1YjcyODA3ZWJiNmQ5YjNiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d_HL8AaP6MDXObpLyjdlVTMkBLc0ICaiITfAEwRlEnw)
> 
> Yes that's intended. 4k Optimal allows only remuxes and web-dls. Encodes are not allowed. Dolby Vision w/o fallback is also banned.
> 
> If there any outliers - like you see a 4k remux or web-dl that you think should be being considered, please let me know through an issue and I'll be more than happy to take a look!

Awesome thank you so much!!! One last question, is it possible to enable fallback somehow? I would love to always get the 4k releases while also getting the best quality for example 1080p releases without having to switch profiles

**Comment by santiagosayshey** [comment]
> Awesome thank you so much!!!
No worries at all, ask as many questions as you need :)

> is it possible to enable fallback somehow? I would love to always get the 4k releases while also getting the best quality for example 1080p releases without having to switch profiles
Definitely something I'll be adding to the 4k profiles soon, I'll create a new issue for this! It might take a while to implement though, I'm having a bit of trouble getting 4k and 1080p to work in the same profile. 

Thanks again for all the awesome feedback!
