### ISSUE TITLE
import issue 0.3

### ISSUE THREAD

**Issue by An7hrax** [santiagosayshey/Profilarr#30]
When trying to import on Linux i received this error:

```
...
FileNotFoundError: [Errno 2] No such file or directory: './imports/custom_formats/Sonarr'
```

So i changed the dir name from sonarr to Sonarr and it worked. then same happend with the profiles but change the name did not work. When it was getting the profiles it needed Sonarr and when importing it needed sonarr.
```

...
FileNotFoundError: [Errno 2] No such file or directory: './imports/quality_profiles/Sonarr/1080p Balanced (Single Grab) (Sonarr).
```

Fixed it by editing the line 191 to (added `.lower()`):
```
with open(f"{config['settings']['import_path']}/quality_profiles/{app.lower()}/{profile_file}", 'r') as file:
```

**Comment by santiagosayshey** [comment]
Hi, I'll get a fix out for this ASAP! Thanks for letting me know!
