### ISSUE TITLE
Inconsitiences with the newest verison.

### ISSUE THREAD

**Issue by Ejz9** [santiagosayshey/Profilarr#31]
Hello, I just recently decided to try this project out after it's mention in the selfh.st blog.

However when running the importer I found issues. Another user opened an issue about their problems and I would also like to bring awareness for those who might not be a technical with code at least.

On line 76 of the importarr.py you have the apps name converted to lowercase which would make sense however it this should also be prefaced elsewhere that the app named is used, specially, the file paths. 

Simple solution I had was remove the `.lower` from the app variable on line 76 and rename the folders in the custom_formats and quality profiles folders.

Regardless, please fix :) Great Work!

**Comment by santiagosayshey** [comment]
> Hello, I just recently decided to try this project out after it's mention in the selfh.st blog.
Woah that's so cool! I had no idea.

> Simple solution I had was remove the .lower from the app variable on line 76 and rename the folders in the custom_formats and quality profiles folders.

Thanks for letting me know, will get a fix out for this ASAP!
